#!/bin/bash -l

PATH_TO_AMEBA_RTOS=$(cat .PATH_TO_AMEBA_RTOS)
AMEBA_PY="python $PATH_TO_AMEBA_RTOS/ameba.py"

PATH_TO_AMEBA_AMAZON_FREERTOS="$PWD"
SOC_INFO_JSON="$PATH_TO_AMEBA_AMAZON_FREERTOS/soc_info.json"

if [ -e "$SOC_INFO_JSON" ]; then
  PATH_TO_BUILD_FOLDER="$PATH_TO_AMEBA_AMAZON_FREERTOS/build_$(python3 -c "import json; print(json.load(open('$SOC_INFO_JSON'))['soc']['name'])")/build"
else
  echo "$SOC_INFO_JSON does not exist, please run \`ameba.py soc\` and choose the SoC for your project."
  exit 1
fi

if [ -d "$PATH_TO_BUILD_FOLDER" ]; then
  $AMEBA_PY clean
  echo "Cleaned amazon-freertos project"
else
  echo "$PATH_TO_BUILD_FOLDER does not exist, clean can only be run when build has occured."
fi
